# task.yml

# Es necesario definir las variables de entorno AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY y AWS_SESSION_TOKEN
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
# export AWS_ACCESS_KEY_ID='AK123'
# export AWS_SECRET_ACCESS_KEY='abc123'

# Disponer del Securiry Group: mi-sg con las reglas deseadas
# Disponer de la clave SSH: mi-sshkey

- hosts: localhost

  tasks:
    - name: Provision a set of instances
      ec2:
        state: 'present'
        group: mi-sg
        key_name: mi-sshkey
        instance_type: t2.micro
        image: "ami-0fc61db8544a617ed"
        region: us-east-1
        wait: true
        count: 1
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2
